(() => {
  const mu=['الٓمٓ','الٓمٓصٓ','الٓر','الٓمٓر','كٓهيعٓصٓ','طه','طسٓمٓ','طسٓ','يسٓ','صٓ','حمٓ','حمٓ عٓسٓقٓ','قٓ','نٓ'];
  const names={ا:'Alif',ل:'Lām',م:'Mīm',ص:'Ṣād',ر:'Rā',ك:'Kāf',ه:'Hā',ي:'Yā',ع:'ʿAyn',ط:'Ṭā',س:'Sīn',ح:'Ḥā',ق:'Qāf',ن:'Nūn'};
  const marks=['َ','ِ','ُ'],sounds=['a','i','u'];
  const letters=['أ','ه','ع','ح','غ','خ','ق','ك','ج','ش','ي','ض','ل','ن','ر','ط','د','ت','ص','س','ز','ظ','ذ','ث','ف','و','ب','م'];
  const roman=['ʾ','h','ʿ','ḥ','gh','kh','q','k','j','sh','y','ḍ','l','n','r','ṭ','d','t','ṣ','s','z','ẓ','dh','th','f','w','b','m'];
  const items={3:mu.map(ar=>({ar,answer:[...ar].filter(x=>names[x]).map(x=>names[x]).join(' · ')})),4:letters.flatMap((l,j)=>marks.map((m,i)=>({ar:(l==='أ'&&i===1?'إ':l)+m,answer:roman[j]+sounds[i]})))};
  const state={3:{mode:'learn',index:0,answers:[]},4:{mode:'learn',index:0,answers:[]}};
  const title={3:'Muqattaʿat Letters',4:'Harakat · Short Vowels'};
  function glyph(ar){return ar.includes('ِ')?`<span class="wb-kasrah" role="img" aria-label="${ar}"><span aria-hidden="true">${ar.replace('ِ','')}</span></span>`:ar;}
  const css=document.createElement('style');css.textContent='.wb-grid{display:grid;direction:rtl!important;gap:1px;background:#cbd5e1;grid-template-columns:repeat(6,minmax(0,1fr))}.wb-grid.mu{grid-template-columns:repeat(4,minmax(0,1fr))}.wb-cell{background:#fffef3;padding:18px 4px;text-align:center;color:#9d174d;min-height:110px}.wb-ar{font-family:Amiri,"Scheherazade New",serif;font-size:48px;line-height:1.9;direction:rtl}.wb-kasrah{display:inline-block;position:relative;line-height:1.55;padding-bottom:.25em;min-width:.65em}.wb-kasrah:after{content:"";position:absolute;width:.28em;height:.045em;background:currentColor;bottom:.1em;left:50%;transform:translateX(-50%) rotate(-18deg)}.wb-box{background:white;border-radius:20px;padding:24px;margin:20px 0}.wb-btn{border:1px solid #cbd5e1;padding:12px 16px;border-radius:12px;margin:4px;background:white}.wb-btn:disabled{opacity:.4}.wb-btn:focus-visible{outline:3px solid #f59e0b}.wb-correct{color:#047857}.wb-wrong{color:#be123c}.wb-actions{display:flex;direction:ltr;justify-content:space-between;flex-wrap:wrap}@media(max-width:420px){.wb-ar{font-size:32px}.wb-cell{min-height:85px}}';document.head.append(css);
  function button(label,action){return `<button type="button" class="wb-btn" onclick="${action}">${label}</button>`;}
  function render(n){const s=state[n],all=items[n],item=all[s.index];const score=s.answers.reduce((a,x,i)=>a+(x===all[i].answer?1:0),0);
    let body='';
    if(s.mode==='learn')body=`<p>Read from the right. ${n===3?'Name each letter separately; madd signs follow the workbook.':'Fatḥah = a, kasrah = i, ḍammah = u. Keep each vowel short. Kasrah is shown below the entire letter.'}</p><div class="wb-grid ${n===3?'mu':''}" dir="rtl">${all.map((x,i)=>`<button class="wb-cell" style="${n===3&&(i===4||i===11)?'grid-column:span 2':''}" onclick="workbookSelect(${n},${i})"><span class="wb-ar">${glyph(x.ar)}</span></button>`).join('')}</div><p id="wb-detail-${n}" class="mt-4">Select a cell to reveal the reading.</p>`;
    else if(s.index===all.length)body=`<h3>Quiz complete: ${score} / ${all.length}</h3>${all.map((x,i)=>`<p class="${s.answers[i]===x.answer?'wb-correct':'wb-wrong'}">${x.ar}: ${s.answers[i]||'Not answered'} — Correct: ${x.answer}</p>`).join('')}${button('Review previous',`workbookStep(${n},-1)`)}${button('Restart',`workbookRestart(${n})`)}`;
    else {const options=n===3?[item.answer,all[(s.index+1)%all.length].answer,all[(s.index+4)%all.length].answer]:sounds.map(x=>item.answer.slice(0,-1)+x);const shift=s.index%3;options.push(...options.splice(0,shift));body=`<p>${s.mode==='quiz'?'Question':'Practice'} ${s.index+1} / ${all.length}</p><p class="wb-ar text-center">${glyph(item.ar)}</p>${s.mode==='practice'?button('Reveal reading',`workbookSelect(${n},${s.index})`):options.map((x,i)=>button(x,`workbookAnswer(${n},${i})`)).join('')}<p id="wb-detail-${n}" aria-live="polite">${s.answers[s.index]===undefined?'':(s.answers[s.index]===item.answer?'Correct. ':'Review. ')+item.answer}</p><div class="wb-actions">${s.index?button('Previous',`workbookStep(${n},-1)`):'<span></span>'}${button(s.index===all.length-1?'Finish & review':'Next',`workbookStep(${n},1)`)}</div>`;}
    document.getElementById('foundation-'+n).innerHTML=`<header><p class="text-accent-500 font-bold">Arabic Foundations · Lesson ${n} · Workbook Lesson ${n+1}</p><h2 class="text-white text-4xl font-bold">${title[n]}</h2></header><div class="wb-box">${['learn','practice','quiz'].map(m=>button(m[0].toUpperCase()+m.slice(1),`workbookMode(${n},'${m}')`)).join('')}<div class="mt-5">${body}</div></div><div class="wb-actions">${button('Previous lesson',n===3?'switchChapter(2)':'openWorkbookLesson(3)')}${n===3?button('Next: Harakat','openWorkbookLesson(4)'):''}</div>`;
  }
  window.workbookMode=(n,m)=>{state[n].mode=m;state[n].index=0;render(n);};
  window.workbookSelect=(n,i)=>{document.getElementById('wb-detail-'+n).textContent=items[n][i].answer;};
  window.workbookAnswer=(n,i)=>{const s=state[n],item=items[n][s.index];const opts=n===3?[item.answer,items[n][(s.index+1)%items[n].length].answer,items[n][(s.index+4)%items[n].length].answer]:sounds.map(x=>item.answer.slice(0,-1)+x);opts.push(...opts.splice(0,s.index%3));s.answers[s.index]=opts[i];render(n);};
  window.workbookStep=(n,d)=>{const s=state[n];if(d>0&&s.mode==='quiz'&&s.answers[s.index]===undefined){document.getElementById('wb-detail-'+n).textContent='Choose an answer first.';return;}s.index=Math.max(0,Math.min(items[n].length-(s.mode==='practice'?1:0),s.index+d));render(n);};
  window.workbookRestart=n=>{state[n].answers=[];state[n].index=0;render(n);};
  window.openWorkbookLesson=n=>{openCourseMenu('foundations');render(n);switchTab('foundation-'+n);document.getElementById('mobile-menu').classList.add('hidden');};
  function mount(){for(const n of [3,4]){const section=document.createElement('section');section.id='foundation-'+n;section.className='tab-content';document.getElementById('ch2-quiz').after(section);for(const suffix of ['', '-m']){const b=document.createElement('button');b.className='w-full text-left p-3 text-slate-300 hover:bg-brand-900 rounded-xl';b.textContent='0'+n+' · '+title[n];b.onclick=()=>openWorkbookLesson(n);document.getElementById('qaida-menu'+suffix).append(b);}render(n);}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
